---
- hosts: base
  become: yes

  tasks:
    - name: Make sure .ssh directory exists
      file:
        path: /home/pi/.ssh
        state: directory
        owner: pi
        group: pi
        mode: 0700

    - name: Update authorized_keys with public SSH key
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: pi
        group: pi
        mode: 0644
      with_items:
        - src: authorized_keys
          dest: /home/pi/.ssh/authorized_keys

    - name: Install convenience tools
      apt:
        name: htop
        state: present

    - name: Configure Vim editor
      copy:
        src: vimrc
        dest: /home/pi/.vimrc
        owner: pi
        group: pi
        mode: 0644
