---
- hosts: all

- import_playbook: base/playbook.yml

- import_playbook: ambient_light_tv/playbook.yml
- import_playbook: entrance_light_and_music/playbook.yml
- import_playbook: kitchen_light/playbook.yml
- import_playbook: kitchen_music/playbook.yml
