#!/bin/bash
set -e

find_files() {
    find \( -path "./venv" -o -path "./.venv" -o -path "./dev-venv" \) -prune -false -o  -name "$1"
}
python_files=$(find_files *.py)
sh_files=$(find_files *.sh)
yml_files=$(find_files *.yml)

printf 'Checking files with shellcheck...\n'
shellcheck ${sh_files}

printf 'Checking files with yamllint...\n'
yamllint ${yml_files}

printf 'Checking files with ansible-lint...\n'
ansible-lint ${yml_files}

printf 'Checking files with pycodestyle...\n'
pycodestyle ${python_files}

printf 'Checking files with black...\n'
black --check --diff --quiet ${python_files}

printf "Done\n"
