---
- hosts: entrance_light_and_music

  vars:
    ansible_python_interpreter: /usr/bin/python3
    base_working_dir: /home/pi/entrance

  tasks:
    - name: Make sure needed Python tools are installed
      apt:
        pkg:
          - python3
          - python3-pip
          - python3-venv
        state: present
      become: yes

    - name: Create directory for code for entrance sensors
      file:
        path: "{{ base_working_dir }}"
        state: directory
        owner: pi
        group: pi
        mode: 0755

    - name: Copy lights controlling scripts
      copy:
        src: "{{ item.src }}"
        dest: "{{ base_working_dir }}"
        owner: pi
        group: pi
        mode: "{{ item.mode }}"
      with_items:
        - {src: "lights_on.sh", mode: "0755"}
        - {src: "lights_off.sh", mode: "0755"}
        - {src: "requirements.txt", mode: "0644"}

    - name: Make sure venv is created
      pip:
        requirements: "{{ base_working_dir }}/requirements.txt"
        virtualenv: "{{ base_working_dir }}/.venv"
        virtualenv_python: python3

    - import_tasks: nexa_switches.yml
