---
- hosts: entrance_light_and_music
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    base_working_dir: /home/pi/entrance

  tasks:
    - name: Make sure needed Python tools are installed
      apt:
        pkg:
          - python3
          - python3-pip
        state: present

    - name: Make sure rpi-rf pip package is installed
      pip:
        name: rpi-rf
        state: present

    - name: Create directory for code for entrance sensors
      file:
        path: "{{ base_working_dir }}"
        state: directory
        owner: pi
        group: pi
        mode: 0755

    - name: Copy lights controlling scripts
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: pi
        group: pi
        mode: 0755
      with_items:
        - src: lights_on.sh
          dest: "{{ base_working_dir }}/lights_on.sh"
        - src: lights_off.sh
          dest: "{{ base_working_dir }}/lights_off.sh"

    - name: Automatically turn on evening lights
      cron:
        name: "Turn on evening lights, {{ item.season }}"
        minute: "0"
        hour: "{{ item.hour }}"
        month: "{{ item.month }}"
        user: pi
        job: "/home/pi/entrance/lights_on.sh >> /tmp/entrance_lights.log 2>&1"
      with_items:
        - season: "summer time"
          hour: "20"
          month: "5-9"
        - season: "autumn time"
          hour: "18"
          month: "10-12"
        - season: "winter time"
          hour: "17"
          month: "1-4"

    - name: Automatically turn off evening lights
      cron:
        name: "Turn off evening lights"
        minute: "00"
        hour: "23"
        user: pi
        job: "/home/pi/entrance/lights_off.sh >> /tmp/entrance_lights.log 2>&1"
