---
- hosts: entrance_light_and_music

  vars:
    ansible_python_interpreter: /usr/bin/python3
    base_working_dir: /home/pi/entrance

  tasks:
    - name: Make sure needed Python tools are installed
      apt:
        pkg:
          - python3
          - python3-pip
          - python3-venv
        state: present
      become: yes

    - name: Create directory for code for entrance sensors
      file:
        path: "{{ base_working_dir }}"
        state: directory
        owner: pi
        group: pi
        mode: 0755

    - name: Copy lights controlling scripts
      copy:
        src: "{{ item.src }}"
        dest: "{{ base_working_dir }}"
        owner: pi
        group: pi
        mode: "{{ item.mode }}"
      with_items:
        - {src: "lights_on.sh", mode: "0755"}
        - {src: "lights_off.sh", mode: "0755"}
        - {src: "requirements.txt", mode: "0644"}

    - name: Make sure venv is created
      pip:
        requirements: "{{ base_working_dir }}/requirements.txt"
        virtualenv: "{{ base_working_dir }}/.venv"
        virtualenv_python: python3

    - name: Automatically turn on evening lights
      cron:
        name: "Turn on evening lights, {{ item.season }}"
        minute: "{{ item.minute | default(0) }}"
        hour: "{{ item.hour }}"
        month: "{{ item.month }}"
        user: pi
        job: "/bin/bash {{ base_working_dir }}/lights_on.sh >> /tmp/entrance_lights.log 2>&1"
      with_items:
        - {season: "summer time", hour: "20", month: "5-9"}
        - {season: "autumn time", hour: "18", month: "3-4,10"}
        - {season: "winter time", hour: "16", month: "11-12,1-2"}

    - name: Automatically turn off evening lights
      cron:
        name: "Turn off evening lights"
        minute: "{{ item.minute }}"
        hour: "{{ item.hour }}"
        user: pi
        job: "/bin/bash {{ base_working_dir }}/lights_off.sh >> /tmp/entrance_lights.log 2>&1"
      with_items:
        - {hour: "22", minute: "30"}

    - import_tasks: nexa_switches.yml
