---
- hosts: base

  vars:
    base_working_dir: /home/pi

  tasks:
    - name: Make sure .ssh directory exists
      file:
        path: "{{ base_working_dir }}/.ssh"
        state: directory
        owner: pi
        group: pi
        mode: 0700

    - name: Update authorized_keys with public SSH key
      copy:
        src: authorized_keys
        dest: "{{ base_working_dir }}/.ssh"
        owner: pi
        group: pi
        mode: 0644

    - name: Set timezone to Europe/Stockholm
      timezone:
        name: Europe/Stockholm
      notify:
        - Restart cron
      become: yes

    - name: Make sure convenience tools are installed
      apt:
        pkg:
          - htop
          - tofrodos
        state: present
      become: yes

    - name: Configure Vim editor
      copy:
        src: vimrc
        dest: "{{ base_working_dir }}/.vimrc"
        owner: pi
        group: pi
        mode: 0644
      notify:
        - Change line endings in Vim configuration

  handlers:
    - name: Restart cron
      service:
        name: cron
        state: restarted
      become: yes

    - name: Change line endings in Vim configuration
      shell: fromdos "{{ base_working_dir }}/.vimrc"
