---
- hosts: base

  tasks:
    - name: Make sure .ssh directory exists
      file:
        path: /home/pi/.ssh
        state: directory
        owner: pi
        group: pi
        mode: 0700

    - name: Update authorized_keys with public SSH key
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: pi
        group: pi
        mode: 0644
      with_items:
        - src: authorized_keys
          dest: /home/pi/.ssh/authorized_keys

    - name: Set timezone to Europe/Stockholm
      timezone:
        name: Europe/Stockholm
      notify:
        - Restart cron
      become: yes

    - name: Make sure convenience tools are installed
      apt:
        name: htop
        state: present
      become: yes

    - name: Configure Vim editor
      copy:
        src: vimrc
        dest: /home/pi/.vimrc
        owner: pi
        group: pi
        mode: 0644

  handlers:
    - name: Restart cron
      service:
        name: cron
        state: restarted
      become: yes
