---
# This is a basic workflow to help you get started with Actions

name: Lint files

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run shellcheck on bash scripts
        run: |
          sudo apt-get install shellcheck
          find "${GITHUB_WORKSPACE}" -name '*.sh' -exec shellcheck {} \;

      - name: Run yamllint
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install yamllint
          python3 -m yamllint "${GITHUB_WORKSPACE}"

      - name: Run pycodestyle
        run: |
          python3 -m pip install pycodestyle
          python3 -m pycodestyle "${GITHUB_WORKSPACE}"

      - name: Run black
        run: |
          python3 -m pip install black
          python3 -m black --check "${GITHUB_WORKSPACE}"

      - name: Run ansible-lint
        run: |
          python3 -m pip install ansible-lint
          python3 -m ansible-lint "${GITHUB_WORKSPACE}"
