---
- hosts: kitchen_music

  vars:
    base_working_dir: /home/pi/music

  tasks:
    - name: Make sure needed tools are installed
      apt:
        pkg:
          - git
          - python
          - python-pip
          - python-virtualenv
          - python-dev
        state: present
      become: yes

    - name: Create directory for code for entrance sensors
      file:
        path: "{{ base_working_dir }}"
        state: directory
        owner: pi
        group: pi
        mode: 0755

    - name: Copy music controlling scripts
      copy:
        src: "{{ item.src }}"
        dest: "{{ base_working_dir }}"
        owner: pi
        group: pi
        mode: "{{ item.mode }}"
      with_items:
        - {src: "kitchenMusic.py", mode: "0755"}
        - {src: "start.sh", mode: "0755"}
        - {src: "requirements.txt", mode: "0644"}

    - name: Clone flicklib repository
      git:
        repo: "https://github.com/PiSupply/Flick.git"
        dest: "{{ base_working_dir }}/Flick/"
        version: fdcfbefc86df493ff78b1035ce30c3ce2129f9b9

    - name: Make sure venv is created
      pip:
        requirements: "{{ base_working_dir }}/requirements.txt"
        virtualenv: "{{ base_working_dir }}/.venv"
      notify:
        - Install and setup flicklib

    - name: Automatically start gesture monitoring script on reboot
      cron:
        name: "Start gesture monitoring script on reboot"
        special_time: reboot
        user: pi
        job: "{{ base_working_dir }}/start.sh >> /tmp/kitchen_music.log 2>&1"

  handlers:
    - name: Install and setup flicklib
      shell: |
        raspi-config nonint do_i2c 0
        cd "{{ base_working_dir }}"/Flick/flick
        source {{ base_working_dir }}/.venv/bin/activate
        python setup.py install
        # here you should reboot the system
      become: yes
      args:
        executable: /bin/bash
